[package]
name = "yew_styles"
version = "0.2.0"
description = "Framework styles for yew"
authors = ["spieljs <spieljs@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/spielrs/yew-styles-page/tree/master/crate/yew_styles"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std_web = ["stdweb", "yew/std_web"]
web_sys = ["web-sys", "yew/web_sys"]

[dependencies]
wasm-bindgen = "0.2"
yew = { version = "0.14", features = ["toml", "yaml", "msgpack", "cbor"], optional = true}
stdweb = { version = "0.4", optional = true}
web-sys = {version = "0.3", features = ["HtmlDocument", "HtmlCollection", "CssStyleDeclaration", "HtmlElement"], optional=true}
uuid = {version= "0.8", features=["v4", "wasm-bindgen", "stdweb"]}
