[package]
name = "yew_styles"
version = "0.1.0"
description = "Framework styles for yew"
authors = ["spieljs <spieljs@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/spielrs/yew-styles-page/tree/master/crate/yew_styles"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
yew = { version = "0.12.0", features = ["toml", "yaml", "msgpack", "cbor"]}
stdweb = "0.4"